before:
  hooks:
    - go mod tidy
builds:
  -
    main: ./cmd/edy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - '^test:'
