name: go-test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  go-test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Test
        run: go test -coverprofile coverage.out -covermode atomic ./...
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8
        with:
          infile: coverage.out
          outfile: coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          path-to-lcov: coverage.lcov
