name: Release

on:
  push:
    tags:
      - v*

jobs:
  setup-release:
    name: Setup release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: Test
        run: go test -race -coverprofile coverage.txt -covermode atomic ./...
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: '*'
      - name: Integration test
        run: sh test/run.sh
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_REGION: ap-northeast-1
      - name: Upload to codecov
        uses: codecov/codecov-action@v1
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ github.token }}
