name: Release

on:
  push:
    tags:
      - v*

jobs:
  setup-release:
    name: Setup release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ github.token }}
