name: test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: Test
        run: go test -covermode atomic ./...
      - name: Install aws cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
      - name: Integration test
        run: sh test/run.sh
